[package]
name = "trpl_blog"
version = "0.1.0"
authors = ["Jacob <jacobbishopxy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

trpl = { path = "../trpl" }
