[package]
name = "trpl_example"
authors = ["Jacob Xie <jacobbishopxy@gmail.com>"]
version = "0.1.0"
edition = "2018"

[dependencies]

trpl = { path = "../trpl" }
trpl_derive = { path = "../trpl/trpl_derive" }
